### ISSUE TITLE
Install the Rollbar plugin'

### ISSUE THREAD

**Issue by moh3n9595** [Resgrid/cordova-plugins-rollbar#11]
Hi, actually I have two issue here;
1. I install plugin and call `this.rollbar.init()` after deice ready, but when I check chrome debugger, I see these warning : 

> Native: tried calling Rollbar.init, but the Rollbar plugin is not installed.

> Install the Rollbar plugin: 'ionic cordova plugin add resgrid-cordova-plugins-rollbar'
2. How can I see js error in Rollbar dashboard?

**Comment by QiaoyuanMaxDeng** [comment]
This plugin is built on top of cordova so it does not work on Chrome. Try on device.

**Comment by QiaoyuanMaxDeng** [comment]
I just tried, it is not working on device either, check this out:
Updated link for Angular 1:
https://github.com/rollbar/rollbar.js#angular-1

and Angular 2 and later:
https://github.com/rollbar/rollbar.js#angular-2-and-later
