### ISSUE TITLE
npm-hosted plugin

### ISSUE THREAD

**Issue by KrisBraun** [Resgrid/cordova-plugins-rollbar#2]
Would it be possible to submit this to npm (http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html)? This looks fantastic, but our project is on PhoneGap Build so needs an npm-hosted plugin.

**Comment by ucswift** [comment]
Kris,
   Yes we will be putting this on NPM shortly as well. Once I've had a chance to fully test it on iOS and Android I will push it out to NPM. I'm currently testing iOS now, Android testing was done last night and looked good.

**Comment by KrisBraun** [comment]
Awesome! Happy to test here, too.

**Comment by ucswift** [comment]
Just wanted to send an update. I think I got PLCrashReporter in correctly, been having a hell of a time with the .framework folders and complication. I did the same with Rollbar's iOS xcode project, but it's not properly picking it up as a framework.

So as of right now, Android works, but iOS won't link.

**Comment by KrisBraun** [comment]
Thanks for the update! Good to know we can give Android a try while we're waiting for iOS. Thanks for all the hard work!

**Comment by ghost** [comment]
Any updates on this for npm? Thanks

**Comment by ucswift** [comment]
I'll be circling back on this either today or tomorrow to revalidate Android and try and finish iOS before pushing to NPM.

**Comment by ghost** [comment]
Awesome thanks.

**Comment by ucswift** [comment]
Just wanted to send you an update. I did some more work on this and got it compiling for iOS and Android. I'm going to do some on device and AppBuilder testing latter this weekend and if that goes well I'll setup the npm hosted plugin.

**Comment by ucswift** [comment]
I've published the plugin to npm (https://www.npmjs.com/package/resgrid-cordova-plugins-rollbar), let me know if there are any issues.

**Comment by hcentelles** [comment]
Is this plugin production ready? Thanks
