### ISSUE TITLE
Name Conflict with Rollbar.js

### ISSUE THREAD

**Issue by brunoluigi** [Resgrid/cordova-plugins-rollbar#3]
Hi folks,

I tried to use the Rollbar official notifier (https://github.com/rollbar/rollbar.js) for Javascript but it causes a conflict with this plugin since both use the Rollbar variable in the global scope.

I actually forked this repository and implemented a quick fix, I changed the variable name to CordovaRollbar, still, I'm not sure if this is the most elegant solution.

**Comment by brunoluigi** [comment]
Actually, I checked out the plugin.xml and found this:

``` xml
    <!-- JavaScript interface -->
    <js-module src="www/rollbar.js" name="RollbarJSInterface">
        <clobbers target="window.Rollbar" />
    </js-module>
```

I think that this would be more appropriate and compliant with the README.md :

``` xml
    <!-- JavaScript interface -->
    <js-module src="www/rollbar.js" name="RollbarJSInterface">
        <clobbers target="cordova.plugins.Rollbar" />
    </js-module>
```

It also solves the issue with the Rollbar.js.

**Comment by Birowsky** [comment]
@brunoluigi is this why i'm getting `TypeError: undefined is not an object (evaluating 'window.cordova.plugins.Rollbar.init')`?

If so, are you satisfied with your approach? Can you give some pointers of how to use it?

**Comment by Birowsky** [comment]
@brunoluigi I'm trying this using your fork, but none of the init() callbacks are firing. Is this expected? How do i know that it's working?

**Comment by brunoluigi** [comment]
@Birowsky I think it shouldn't affect any behavior. The only thing I changed was the place where the module is mounted to cordova.plugins.Rollbar instead of window.Rollbar.

**Comment by rnagella** [comment]
@brunoluigi I had the same issue with this plugin usage today, I tried your solution and it is working as expected i.e., to use  `cordova.plugins.Rollbar.init()` instead `window.cordova.plugins.Rollbar.init()`
