### ISSUE TITLE
'Rollbar/Rollbar.h' file not found when ionic build ios

### ISSUE THREAD

**Issue by giszhou** [Resgrid/cordova-plugins-rollbar#6]
In file included from /Users/joez/Documents/code/ionic-demo/platforms/ios/ionic-demo/Plugins/resgrid.cordova.plugins.rollbar/CDVRollbar.m:7:
ionic-demo/Plugins/resgrid.cordova.plugins.rollbar/CDVRollbar.h:9:9: fatal error: 'Rollbar/Rollbar.h' file not found
#import <Rollbar/Rollbar.h>
        ^
1 error generated.

**Comment by AugusDogus** [comment]
I am also experiencing this issue.

**Comment by lennycampino** [comment]
Same

**Comment by AugusDogus** [comment]
Has anyone found a fix or workaround?

**Comment by pe1o2pl** [comment]
Same issue in the ionic project: 

```
fatal error: 'Rollbar/Rollbar.h' file not found
        #import <Rollbar/Rollbar.h>
             
        1 error generated.  
```      

ionic info:

  ```
  @ionic/cli-utils : 1.2.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.2.0
    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : ios 4.3.1
    Ionic Framework                 : ionic-angular 3.3.0
    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.1 Build version 8E1000a 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
```

**Comment by emilyemorehouse** [comment]
If anyone needs a fix for this, I narrowed it down to an issue with the symbolic links to the Rollbar.framework files. I removed the symlinks and used regular paths and it fixed the issue.

This change is implemented in my fork of the repo (https://github.com/emilyemorehouse/cordova-plugins-rollbar), but check out the README before using it as I changed the target clobber name (from #3).

**Comment by QiaoyuanMaxDeng** [comment]
Updated link for Angular 1:
https://github.com/rollbar/rollbar.js#angular-1

and Angular 2 and later:
https://github.com/rollbar/rollbar.js#angular-2-and-later

**Comment by blueromans** [comment]
and `pod "Rollbar", "~> 1.0.0-alpha11" ` platforms/ios/ Podfile. then run pod install
