### ISSUE TITLE
Does not report errors (using ionic)

### ISSUE THREAD

**Issue by AmitMY** [Resgrid/cordova-plugins-rollbar#7]
I am using this plugin in my Cordova project, using the ionic native thing here - https://ionicframework.com/docs/v2/native/rollbar/
And after I do:
```
import { Rollbar } from 'ionic-native';

Rollbar.init();
```

And then:
`throw new Error("example error")` and running on an android device, Rollbar's website still says:
>  Waiting for data from your Ionic app...
This page will update once we receive an error from your app.

- How can I see if I perhaps did something wrong?
- If this is not the way to track errors, what is?

**Comment by sebestenyb** [comment]
I think your issue is that the plugin only catches native exceptions, not JS ones.
And unfortunately it **doesn't expose other methods** of the underlying Rollbar Android SDK.

Otherwise we could do something like this:

```
class MyErrorHandler implements ErrorHandler {
  handleError(err: any): void {
    Rollbar.reportException(err)
  }
}

@NgModule({
  providers: [{ provide: ErrorHandler, useClass: MyErrorHandler }]
})
class AppModule {}
```

1. https://ionicframework.com/docs/v2/api/util/IonicErrorHandler/
2. https://rollbar.com/docs/notifier/rollbar-android/

@ucswift would you consider adding at least that method? It would be an immense help for us :)

Cheers, Sebi

**Comment by ucswift** [comment]
@AmitMY Sorry for the delay and @sebestenyb you are correct. For our Ionic apps we have this rollbar setup for only the native issues then use the standard Rollbar JS inclusion for catching the webview/js issues.

I'm going to try and put some time against this soon to add the support you want @sebestenyb.

**Comment by AmitMY** [comment]
@ucswift I made a pull request for that. If you can check it out, and merge, that solves this issue.

**Comment by saschwarz** [comment]
On the JS side Rollbar has just released 2.0 as an npm package along with code for integrating it into Angular 2+. It seems to work fine in my Ionic 2+ app:

https://github.com/rollbar/rollbar.js#angular-2

I only had to change the import to:

    import * as Rollbar from 'rollbar';

**Comment by QiaoyuanMaxDeng** [comment]
Updated link for Angular 1:
https://github.com/rollbar/rollbar.js#angular-1

and Angular 2 and later:
https://github.com/rollbar/rollbar.js#angular-2-and-later

**Comment by MichaelMarner** [comment]
I also maintain an Angular 2+ wrapper for Rollbar:

https://github.com/NextFaze/angular-rollbar
